### ISSUE TITLE
Not working in Oreo, cannot see buttons.

### ISSUE THREAD

**Issue by AVINASH21AK** [Vorlonsoft/AndroidRate#13]

**Comment by AlexanderLS** [comment]
Hi @AVINASH21AK 

It's Oreo screenshot on the REEADME.md. Could you provide additional details 

![AndroidRate animated screenshots](https://raw.githubusercontent.com/Vorlonsoft/AndroidRate/master/screenshots/screenshots_720x1280.gif)

**Comment by AlexanderLS** [comment]
All 4 Dialog variants were tested on API28, API22, API19, API16 and API10. We don't find "cannot see buttons" errors. Please provide additional information/logs and we will reopen this ticket or create new one by yourself. Thank you.

1st Dialog variant (CLASSIC-non-AppCompat):

    .setDialogType(DialogType.CLASSIC)
    .setDialogManagerFactory(null)

2nd Dialog variant (CLASSIC-AppCompat):

    DialogManager.Factory appCompatDialogManagerFactory = new AppCompatDialogManager.Factory();
    ...
    .setDialogType(DialogType.CLASSIC)
    .setDialogManagerFactory(appCompatDialogManagerFactory)

3rd Dialog variant (APPLE-non-AppCompat):

    .setDialogType(DialogType.APPLE)
    .setDialogManagerFactory(null)

4th Dialog variant (APPLE-AppCompat):

    DialogManager.Factory appCompatDialogManagerFactory = new AppCompatDialogManager.Factory();
    ...
    .setDialogType(DialogType.APPLE)
    .setDialogManagerFactory(appCompatDialogManagerFactory)
