### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by dhruv2295** [Vorlonsoft/AndroidRate#14]
I am getting this error when i implement this library in my project.

**Comment by AlexanderLS** [comment]
Hi, @dhruv2295 

Are you use
```
dependencies {
    implementation "com.vorlonsoft:androidrate:+"
}
```
instead of
```
dependencies {
    implementation "com.vorlonsoft:androidrate:1.2.1"
}
```
or
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
dependencies {
    implementation "com.vorlonsoft:androidrate:1.2.5-SNAPSHOT"
}
```
?

Can you see the "Android resource linking failed" error if you use a version name instead of `+`? If you can see please provide me your `dependencies` section from your `build.gradle` file. Thanks.

**Comment by saadrehman1** [comment]
hey, I have used both of the methods but I still get an error. 
"Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-56:19 to override."


My dependencies in the build.gradle file are as follows.:
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'gun0912.ted:tedpermission:2.2.2'
    implementation 'com.github.medyo:android-about-page:1.2.4'
    implementation "com.vorlonsoft:androidrate:1.2.5-SNAPSHOT"
}
What is the problem?

**Comment by AlexanderLS** [comment]
Hi @saadrehman1, @dhruv2295  

Add `tools:replace="android:appComponentFactory"` to element at `AndroidManifest.xml:9:5-56:19` to override or [Migrate to AndroidX](https://developer.android.com/jetpack/androidx/migrate)

Is it work for you?

**Comment by AlexanderLS** [comment]
@saadrehman1, @dhruv2295, ok, I'll close this issue. Thank you.
