### ISSUE TITLE
Logo for AndroidRate

### ISSUE THREAD

**Issue by hafizahmmed** [Vorlonsoft/AndroidRate#2]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change. 

![androidrate-01](https://user-images.githubusercontent.com/38810169/40302715-de280a78-5d11-11e8-9774-5aebba288ba6.jpg)

**Comment by AlexanderLS** [comment]
Hi @hafizahmmed,

Thank you. I like it. I want to use this icon in this project, Could you please give me the source file?

Best regards,
Alexander Savin

**Comment by hafizahmmed** [comment]
hello,
good day sir, 

here is source file : https://drive.google.com/open?id=1gGy433fjdalPC3adMXpcFpdeZljkPl-Y

and

plzz check pull request #3


Thank you for like my design

**Comment by AlexanderLS** [comment]
Hi @hafizahmmed,,

Thank you.

- Pull request #3 was merged on May 24;
- Sample launcher icon was updated;
![Sample launcher icon](https://raw.githubusercontent.com/Vorlonsoft/AndroidRate/master/sample/src/main/ic_launcher-web.png)
- Animated screenshots was updated;
![AndroidRate animated screenshots](https://raw.githubusercontent.com/Vorlonsoft/AndroidRate/master/screenshots/screenshots_360x640.gif)
- README.md was updated.

Best regards,
Alexander Savin
