### ISSUE TITLE
dialog error

### ISSUE THREAD

**Issue by kasmadi17** [Vorlonsoft/AndroidRate#5]
dialog error when app just back to home, when i open app again dialog error "window manager bad token".
use AppRate.with(this).clearAgreeShowDialog() but nothing change. oh ya apprate.debug(true).
 sorry my english very bad. but android rate libarary is awesome

**Comment by AlexanderLS** [comment]
Hi @kasmadi17 

We investigated this issue and fixed it in [LIBbb10829](https://github.com/Vorlonsoft/AndroidRate/commit/9aeaae7781e922afb95970a256878608d7f4fbc4). It's workaround. We need to know your Android OS version and phone or emulator you used?

`window manager bad token` error is common if developer forgot `if (!activity.isFinishing()) {` check before `dialog.show();`, but library has it.

Thanks.

**Comment by kasmadi17** [comment]
thanks @AlexanderLS . xioami 3s os marshmallow . but my app set to run in background

**Comment by AlexanderLS** [comment]
Hi @kasmadi17, 

[LIBbb10829](https://github.com/Vorlonsoft/AndroidRate/commit/9aeaae7781e922afb95970a256878608d7f4fbc4) was fix, not workaround. It's only thing that we can do on the library side. Users won't see any errors.

On the application side you can use `AppRate.with(this).dismissRateDialog()`. It dismisses Rate Dialog, removing it from the screen, and clears weak reference dialog object.

Thanks.

**Comment by AlexanderLS** [comment]
Hi @kasmadi17,

For example try to check `AppRate.with(this).isShowingRateDialog()` before your app goes to the background:
* if true --> call `AppRate.with(this).dismissRateDialog()`, then call `AppRate.with(this).showRateDialog(Activity)` after your app returns to the foreground
* if false --> do nothing

Depends on your app behavior...

**Comment by kasmadi17** [comment]
oke thanks @AlexanderLS

**Comment by AlexanderLS** [comment]
Hi @kasmadi17,

Their fix for related #6 - [LIBbb20831](https://github.com/Vorlonsoft/AndroidRate/commit/3576646d74d4734c48d875c007eb69b2bb397103)
