### ISSUE TITLE
Set OnClickListner To Nigative Button

### ISSUE THREAD

**Issue by simoclick** [Vorlonsoft/AndroidRate#7]
i add this to onBackPressed when i click back button rating dialog launch all good but i want if you click on "No Thanks" Button dismiss dialog and exit from App

**Comment by AlexanderLS** [comment]
Hi @simoclick ,

You can use OnClickButtonListener(). Change `MainActivity` to your Activity's name:

                // Java 7- start
                AppRate.with(this).setOnClickButtonListener(new OnClickButtonListener() {
                    @Override
                    public void onClickButton(final byte which) {
                        if (which == DialogInterface.BUTTON_NEGATIVE) {
                            MainActivity.super.onBackPressed();
                        }
                    }
                })
                // Java 7- end
                // Java 8+ start
                AppRate.with(this)..setOnClickButtonListener(which -> {
                    if (which == DialogInterface.BUTTON_NEGATIVE) {
                        MainActivity.super.onBackPressed();
                    }
                })
                // Java 8+ end

**Comment by AlexanderLS** [comment]
Hi @simoclick ,

See related issue - https://github.com/hotchemi/Android-Rate/issues/115

Fix for related issue - https://github.com/Vorlonsoft/AndroidRate/commit/91a5e3eb27572e5d41ff879c5f2b04d38dd5efeb
