### ISSUE TITLE
how to use AppCompat theme dialog for Api <=17

### ISSUE THREAD

**Issue by khalid-mahmood** [Vorlonsoft/AndroidRate#8]
![screenshot_1535933267](https://user-images.githubusercontent.com/6528169/44962288-635e8100-af37-11e8-9f5d-ddd5d5511ce7.png)
this is preview on kitkat

**Comment by AlexanderLS** [comment]
Hi @khalid-mahmood ,

The AndroidRate library allows you to use a Fully Customizable Dialog (from the support library).

1. You must implement **DialogManager Interface** (`DialogManager.java` file from AndroidRate library).
1.1. You can use `DefaultDialogManager.java` file from Android Rate library as example of implementation of DialogManager Interface.
1.2. Or you can extend **Default**DialogManager Class (`DefaultDialogManager.java` file from AndroidRate library).
2. Use 

        DialogManager.Factory dialogManagerFactory = new YourImplementedDialogManager.Factory();
        AppRate.with(this).setDialogManagerFactory(dialogManagerFactory);

**Comment by AlexanderLS** [comment]
Hi @khalid-mahmood 

I added [LIBff10904 AppCompatDialogManager](https://github.com/Vorlonsoft/AndroidRate/commit/e1a9974bb3a93742b0021f913cfa6cea04c24275) feature.

For `androidx.appcompat.app.AlertDialog` use:

    // NOTE: For API from 9 to 13 `android.app.AlertDialog` will be used.
    DialogManager.Factory appCompatDialogManagerFactory = new AppCompatDialogManager.Factory();
    AppRate.with(this).setDialogManagerFactory(appCompatDialogManagerFactory);

Also I added [LIBff30904 AppCompatDialogManager example of use](https://github.com/Vorlonsoft/AndroidRate/commit/502441f5b5b3c5b8910942fd12ed053de8fa7c9d)

Also you can do your implementation of DialogManager interface

**Comment by khalid-mahmood** [comment]
@AlexanderLS thanks.
newly changes isn't available through gradle build. can you also do that please.!

**Comment by AlexanderLS** [comment]
Hi @khalid-mahmood ,

Changes will be included in the next release 1.2.1 Osaka.

If you don't want to wait for the next release, you can add the Maven Central Snapshots repository:

    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }

and add the following dependency

    dependencies {
        implementation "com.vorlonsoft:androidrate:1.2.1-SNAPSHOT"
    }

**Comment by AlexanderLS** [comment]
Hi @khalid-mahmood ,

AndroidRate 1.2.1 Osaka released, you can use:

    implementation "com.vorlonsoft:androidrate:1.2.1"

**Comment by khalid-mahmood** [comment]
got this error after update to 1.2.1
Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy, sources=[Unknown source file], tool name=Optional.of(D8)}

with 1.2.0 no error
