### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Vorlonsoft/AndroidRate#9]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by AlexanderLS** [comment]
Hi @mansya ,

Thank you! I like the project's current logo developed by [Hafiz Ahmed](https://github.com/hafizahmmed). I don't think that the project should change it:

![AndroidRate logo](https://github.com/Vorlonsoft/AndroidRate/raw/master/logo/192px.png)

![Sample launcher icon](https://raw.githubusercontent.com/Vorlonsoft/AndroidRate/master/sample/src/main/ic_launcher-web.png)

![AndroidRate animated screenshots](https://raw.githubusercontent.com/Vorlonsoft/AndroidRate/master/screenshots/screenshots_360x640.gif)
